-- Create Message_Library table
CREATE TABLE IF NOT EXISTS Message_Library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relationship TEXT NOT NULL,
    tone TEXT NOT NULL,
    message_text TEXT NOT NULL,
    provider TEXT DEFAULT 'ai',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_relationship_tone ON Message_Library(relationship, tone);

-- Enable Row Level Security
ALTER TABLE Message_Library ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to read
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'message_library' AND policyname = 'Allow public read access'
    ) THEN
        CREATE POLICY "Allow public read access" ON Message_Library FOR SELECT USING (true);
    END IF;
END $$;

-- Create policy to allow public to insert
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'message_library' AND policyname = 'Allow public insert access'
    ) THEN
        CREATE POLICY "Allow public insert access" ON Message_Library FOR INSERT WITH CHECK (true);
    END IF;
END $$;
